### ISSUE TITLE
Installation instructions unclear

### ISSUE THREAD

**Issue by steven42tokyo** [0x050f/libft-war-machine#38]
In the getting started section, after cloning the readme, it says:
"If you run the script for the first time"

Which script is meant by "the script"? This is unclear. The readme should be changed to clarify this. Furthermore, it is a better practice that one can simply cd into a project directory and run make and everything should be taken care of. That standard practice essentially standardizes installation procedures so that one does not need to bother thinking about what .sh file should be run, etc.

**Comment by 0x050f** [comment]
The procedure is described in the 'Running' section, and seems clear, but if you think about a better formulation you can still do a PR.
For the standard practice, have you a documentation cheet RFC or something about it ? Because if you are talking about 42 units testing standards, I would not call it that way because it's certainly not good practice.
Anyway if you want to make any changes on this repository, you can still do a PR, and I'll review it.
I don't have time for this kind of project and it only helps me when I did libft 3.5 years ago, I will not make any changes by myself.
